/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[18] = {6, 3, 0, 4, 8, 12, 0, 1, 2, 3, 0, 1, 2, 4, 0, 1, 2, 5};
static const casadi_int casadi_s1[21] = {3, 6, 0, 3, 6, 9, 10, 11, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[39] = {6, 6, 0, 6, 12, 18, 22, 26, 30, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 0, 1, 2, 4, 0, 1, 2, 5};
static const casadi_int casadi_s3[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[6] = {0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[30] = {6, 6, 0, 6, 11, 15, 18, 20, 21, 0, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 5, 5};
static const casadi_int casadi_s6[30] = {6, 6, 0, 1, 3, 6, 10, 15, 21, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s8[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s9[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s10[3] = {0, 0, 0};

static const casadi_real casadi_c0[36] = {1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.};

/* Drone_ode_expl_ode_fun:(i0[12],i1[4],i2[])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+6, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+30, *w14=w+42, *w15=w+48, *w16=w+84, *w17=w+120, *w18=w+156, *w19=w+165, *w20=w+174, *w21=w+183, *w22=w+192, *w23=w+210, *w24=w+228, *w25=w+231, *w26=w+243, *w27=w+255, *w28=w+285, *w29=w+315, *w30=w+351, *w31=w+357, *w32=w+363, *w33=w+369;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = input[0][2] */
  w3 = arg[0] ? arg[0][2] : 0;
  /* #4: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #7: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #8: @8 = input[0][7] */
  w8 = arg[0] ? arg[0][7] : 0;
  /* #9: @9 = input[0][8] */
  w9 = arg[0] ? arg[0][8] : 0;
  /* #10: @10 = input[0][9] */
  w10 = arg[0] ? arg[0][9] : 0;
  /* #11: @11 = input[0][10] */
  w11 = arg[0] ? arg[0][10] : 0;
  /* #12: @12 = input[0][11] */
  w12 = arg[0] ? arg[0][11] : 0;
  /* #13: @13 = vertcat(@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @14 = @13[6:12] */
  for (rr=w14, ss=w13+6; ss!=w13+12; ss+=1) *rr++ = *ss;
  /* #15: (@0[:6] = @14) */
  for (rr=w0+0, ss=w14; rr!=w0+6; rr+=1) *rr = *ss++;
  /* #16: @14 = zeros(6x1) */
  casadi_clear(w14, 6);
  /* #17: @15 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 36, w15);
  /* #18: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #19: @1 = 1.52899e-08 */
  w1 = 1.5289870926215137e-08;
  /* #20: (@16[0] = @1) */
  for (rr=w16+0, ss=(&w1); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #21: @1 = 1.52899e-08 */
  w1 = 1.5289870926215137e-08;
  /* #22: (@16[7] = @1) */
  for (rr=w16+7, ss=(&w1); rr!=w16+8; rr+=1) *rr = *ss++;
  /* #23: @1 = 1.52899e-08 */
  w1 = 1.5289870926215137e-08;
  /* #24: (@16[14] = @1) */
  for (rr=w16+14, ss=(&w1); rr!=w16+15; rr+=1) *rr = *ss++;
  /* #25: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #26: (@16[21] = @1) */
  for (rr=w16+21, ss=(&w1); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #27: @1 = -1.19721e-08 */
  w1 = -1.1972093549697218e-08;
  /* #28: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #29: @1 = (@1*@2) */
  w1 *= w2;
  /* #30: (@16[33] = @1) */
  for (rr=w16+33, ss=(&w1); rr!=w16+34; rr+=1) *rr = *ss++;
  /* #31: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #32: @2 = 1.03024e-08 */
  w2 = 1.0302371890782026e-08;
  /* #33: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #34: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #35: @2 = (@2*@3) */
  w2 *= w3;
  /* #36: @1 = (@1+@2) */
  w1 += w2;
  /* #37: @2 = 8.6825e-09 */
  w2 = 8.6825002969186300e-09;
  /* #38: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #39: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #40: @2 = (@2*@3) */
  w2 *= w3;
  /* #41: @1 = (@1-@2) */
  w1 -= w2;
  /* #42: (@16[28] = @1) */
  for (rr=w16+28, ss=(&w1); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #43: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #44: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #45: @1 = (@1*@2) */
  w1 *= w2;
  /* #46: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #47: @1 = (@1*@2) */
  w1 *= w2;
  /* #48: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #49: @1 = (@1*@2) */
  w1 *= w2;
  /* #50: @2 = 8.6825e-09 */
  w2 = 8.6825002969186300e-09;
  /* #51: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #52: @2 = (@2*@3) */
  w2 *= w3;
  /* #53: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #54: @2 = (@2*@3) */
  w2 *= w3;
  /* #55: @3 = sin(@4) */
  w3 = sin( w4 );
  /* #56: @2 = (@2*@3) */
  w2 *= w3;
  /* #57: @1 = (@1-@2) */
  w1 -= w2;
  /* #58: (@16[34] = @1) */
  for (rr=w16+34, ss=(&w1); rr!=w16+35; rr+=1) *rr = *ss++;
  /* #59: @1 = -1.19721e-08 */
  w1 = -1.1972093549697218e-08;
  /* #60: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #61: @1 = (@1*@2) */
  w1 *= w2;
  /* #62: (@16[23] = @1) */
  for (rr=w16+23, ss=(&w1); rr!=w16+24; rr+=1) *rr = *ss++;
  /* #63: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #64: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #65: @1 = (@1*@2) */
  w1 *= w2;
  /* #66: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #67: @1 = (@1*@2) */
  w1 *= w2;
  /* #68: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #69: @1 = (@1*@2) */
  w1 *= w2;
  /* #70: @2 = 8.6825e-09 */
  w2 = 8.6825002969186300e-09;
  /* #71: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #72: @2 = (@2*@3) */
  w2 *= w3;
  /* #73: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #74: @2 = (@2*@3) */
  w2 *= w3;
  /* #75: @3 = sin(@4) */
  w3 = sin( w4 );
  /* #76: @2 = (@2*@3) */
  w2 *= w3;
  /* #77: @1 = (@1-@2) */
  w1 -= w2;
  /* #78: (@16[29] = @1) */
  for (rr=w16+29, ss=(&w1); rr!=w16+30; rr+=1) *rr = *ss++;
  /* #79: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #80: @2 = 1.19721e-08 */
  w2 = 1.1972093549697218e-08;
  /* #81: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #82: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #83: @2 = (@2*@3) */
  w2 *= w3;
  /* #84: @1 = (@1-@2) */
  w1 -= w2;
  /* #85: @2 = 1.03024e-08 */
  w2 = 1.0302371890782026e-08;
  /* #86: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #87: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #88: @2 = (@2*@3) */
  w2 *= w3;
  /* #89: @1 = (@1+@2) */
  w1 += w2;
  /* #90: @2 = 1.03024e-08 */
  w2 = 1.0302371890782026e-08;
  /* #91: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #92: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #93: @2 = (@2*@3) */
  w2 *= w3;
  /* #94: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #95: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #96: @2 = (@2*@3) */
  w2 *= w3;
  /* #97: @1 = (@1-@2) */
  w1 -= w2;
  /* #98: @2 = 8.6825e-09 */
  w2 = 8.6825002969186300e-09;
  /* #99: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #100: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #101: @2 = (@2*@3) */
  w2 *= w3;
  /* #102: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #103: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #104: @2 = (@2*@3) */
  w2 *= w3;
  /* #105: @1 = (@1+@2) */
  w1 += w2;
  /* #106: (@16[35] = @1) */
  for (rr=w16+35, ss=(&w1); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #107: @17 = zeros(6x6) */
  casadi_clear(w17, 36);
  /* #108: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #109: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #110: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #111: @1 = cos(@6) */
  w1 = cos( w6 );
  /* #112: (@20[0] = @1) */
  for (rr=w20+0, ss=(&w1); rr!=w20+1; rr+=1) *rr = *ss++;
  /* #113: @1 = sin(@6) */
  w1 = sin( w6 );
  /* #114: @1 = (-@1) */
  w1 = (- w1 );
  /* #115: (@20[3] = @1) */
  for (rr=w20+3, ss=(&w1); rr!=w20+4; rr+=1) *rr = *ss++;
  /* #116: @1 = sin(@6) */
  w1 = sin( w6 );
  /* #117: (@20[1] = @1) */
  for (rr=w20+1, ss=(&w1); rr!=w20+2; rr+=1) *rr = *ss++;
  /* #118: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #119: (@20[4] = @6) */
  for (rr=w20+4, ss=(&w6); rr!=w20+5; rr+=1) *rr = *ss++;
  /* #120: @6 = 1 */
  w6 = 1.;
  /* #121: (@20[8] = @6) */
  for (rr=w20+8, ss=(&w6); rr!=w20+9; rr+=1) *rr = *ss++;
  /* #122: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #123: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #124: (@21[0] = @6) */
  for (rr=w21+0, ss=(&w6); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #125: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #126: (@21[6] = @6) */
  for (rr=w21+6, ss=(&w6); rr!=w21+7; rr+=1) *rr = *ss++;
  /* #127: @6 = 1 */
  w6 = 1.;
  /* #128: (@21[4] = @6) */
  for (rr=w21+4, ss=(&w6); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #129: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #130: @6 = (-@6) */
  w6 = (- w6 );
  /* #131: (@21[2] = @6) */
  for (rr=w21+2, ss=(&w6); rr!=w21+3; rr+=1) *rr = *ss++;
  /* #132: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #133: (@21[8] = @6) */
  for (rr=w21+8, ss=(&w6); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #134: @19 = mac(@20,@21,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #135: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #136: @6 = 1 */
  w6 = 1.;
  /* #137: (@20[0] = @6) */
  for (rr=w20+0, ss=(&w6); rr!=w20+1; rr+=1) *rr = *ss++;
  /* #138: @6 = cos(@4) */
  w6 = cos( w4 );
  /* #139: (@20[4] = @6) */
  for (rr=w20+4, ss=(&w6); rr!=w20+5; rr+=1) *rr = *ss++;
  /* #140: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #141: @6 = (-@6) */
  w6 = (- w6 );
  /* #142: (@20[7] = @6) */
  for (rr=w20+7, ss=(&w6); rr!=w20+8; rr+=1) *rr = *ss++;
  /* #143: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #144: (@20[5] = @6) */
  for (rr=w20+5, ss=(&w6); rr!=w20+6; rr+=1) *rr = *ss++;
  /* #145: @6 = cos(@4) */
  w6 = cos( w4 );
  /* #146: (@20[8] = @6) */
  for (rr=w20+8, ss=(&w6); rr!=w20+9; rr+=1) *rr = *ss++;
  /* #147: @18 = mac(@19,@20,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #148: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #149: @22 = horzcat(@18, @19) */
  rr=w22;
  for (i=0, cs=w18; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<9; ++i) *rr++ = *cs++;
  /* #150: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #151: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #152: @24 = ones(3x3,3nz) */
  casadi_fill(w24, 3, 1.);
  /* #153: @25 = horzcat(@18, @24) */
  rr=w25;
  for (i=0, cs=w18; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #154: @26 = @25' */
  casadi_trans(w25,casadi_s1, w26, casadi_s0, iw);
  /* #155: @27 = horzcat(@23, @26) */
  rr=w27;
  for (i=0, cs=w23; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<12; ++i) *rr++ = *cs++;
  /* #156: @28 = @27' */
  casadi_trans(w27,casadi_s2, w28, casadi_s2, iw);
  /* #157: @29 = zeros(6x6) */
  casadi_clear(w29, 36);
  /* #158: @6 = 5.96654e-08 */
  w6 = 5.9665382678984715e-08;
  /* #159: (@29[14] = @6) */
  for (rr=w29+14, ss=(&w6); rr!=w29+15; rr+=1) *rr = *ss++;
  /* #160: @6 = 7.69322e-09 */
  w6 = 7.6932224647131893e-09;
  /* #161: (@29[35] = @6) */
  for (rr=w29+35, ss=(&w6); rr!=w29+36; rr+=1) *rr = *ss++;
  /* #162: @17 = mac(@28,@29,@17) */
  casadi_mtimes(w28, casadi_s2, w29, casadi_s3, w17, casadi_s3, w, 0);
  /* #163: @16 = (@16+@17) */
  for (i=0, rr=w16, cs=w17; i<36; ++i) (*rr++) += (*cs++);
  /* #164: @15 = (@16\@15) */
  rr = w15;
  ss = w16;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[21], r[21], beta[6], w[12];
    casadi_qr(casadi_s3, ss, w, casadi_s5, v, casadi_s6, r, beta, casadi_s4, casadi_s4);
    casadi_qr_solve(rr, 6, 0, casadi_s5, v, casadi_s6, r, beta, casadi_s4, casadi_s4, w);
  }
  /* #165: @30 = zeros(6x1) */
  casadi_clear(w30, 6);
  /* #166: @31 = zeros(6x1) */
  casadi_clear(w31, 6);
  /* #167: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #168: @6 = 1.19785e-07 */
  w6 = 1.1978464639568519e-07;
  /* #169: (@16[14] = @6) */
  for (rr=w16+14, ss=(&w6); rr!=w16+15; rr+=1) *rr = *ss++;
  /* #170: @6 = 6.61206e-07 */
  w6 = 6.6120603053419877e-07;
  /* #171: (@16[21] = @6) */
  for (rr=w16+21, ss=(&w6); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #172: @6 = 3.22793e-07 */
  w6 = 3.2279346087386091e-07;
  /* #173: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #174: @6 = 3.54492e-08 */
  w6 = 3.5449199590826116e-08;
  /* #175: (@16[35] = @6) */
  for (rr=w16+35, ss=(&w6); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #176: @6 = 0 */
  w6 = 0.;
  /* #177: @1 = 0 */
  w1 = 0.;
  /* #178: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #179: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #180: @7 = input[1][2] */
  w7 = arg[1] ? arg[1][2] : 0;
  /* #181: @8 = input[1][3] */
  w8 = arg[1] ? arg[1][3] : 0;
  /* #182: @32 = vertcat(@6, @1, @2, @3, @7, @8) */
  rr=w32;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w8;
  /* #183: @31 = mac(@16,@32,@31) */
  for (i=0, rr=w31; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #184: @32 = zeros(6x1) */
  casadi_clear(w32, 6);
  /* #185: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #186: @6 = 5.53292e-07 */
  w6 = 5.5329234373894511e-07;
  /* #187: (@16[21] = @6) */
  for (rr=w16+21, ss=(&w6); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #188: @6 = 2.96549e-07 */
  w6 = 2.9654855202952268e-07;
  /* #189: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #190: @33 = @13[:6] */
  for (rr=w33, ss=w13+0; ss!=w13+6; ss+=1) *rr++ = *ss;
  /* #191: @32 = mac(@16,@33,@32) */
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w33+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #192: @31 = (@31-@32) */
  for (i=0, rr=w31, cs=w32; i<6; ++i) (*rr++) -= (*cs++);
  /* #193: @32 = zeros(6x1) */
  casadi_clear(w32, 6);
  /* #194: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #195: @6 = 1.12997e-07 */
  w6 = 1.1299677466912913e-07;
  /* #196: (@16[14] = @6) */
  for (rr=w16+14, ss=(&w6); rr!=w16+15; rr+=1) *rr = *ss++;
  /* #197: @6 = 1.45319e-07 */
  w6 = 1.4531883552671554e-07;
  /* #198: (@16[21] = @6) */
  for (rr=w16+21, ss=(&w6); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #199: @6 = 6.28845e-08 */
  w6 = 6.2884489814184357e-08;
  /* #200: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #201: @6 = 2.86876e-08 */
  w6 = 2.8687586626555581e-08;
  /* #202: (@16[35] = @6) */
  for (rr=w16+35, ss=(&w6); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #203: @33 = @13[6:12] */
  for (rr=w33, ss=w13+6; ss!=w13+12; ss+=1) *rr++ = *ss;
  /* #204: @32 = mac(@16,@33,@32) */
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w33+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #205: @31 = (@31-@32) */
  for (i=0, rr=w31, cs=w32; i<6; ++i) (*rr++) -= (*cs++);
  /* #206: @32 = zeros(6x1) */
  casadi_clear(w32, 6);
  /* #207: @6 = 1.49994e-07 */
  w6 = 1.4999363378617051e-07;
  /* #208: (@32[2] = @6) */
  for (rr=w32+2, ss=(&w6); rr!=w32+3; rr+=1) *rr = *ss++;
  /* #209: @31 = (@31+@32) */
  for (i=0, rr=w31, cs=w32; i<6; ++i) (*rr++) += (*cs++);
  /* #210: @30 = mac(@28,@31,@30) */
  casadi_mtimes(w28, casadi_s2, w31, casadi_s7, w30, casadi_s7, w, 0);
  /* #211: @31 = zeros(6x1) */
  casadi_clear(w31, 6);
  /* #212: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #213: @6 = 1.03024e-08 */
  w6 = 1.0302371890782026e-08;
  /* #214: @6 = (@6*@12) */
  w6 *= w12;
  /* #215: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #216: @6 = (@6*@1) */
  w6 *= w1;
  /* #217: @1 = 2 */
  w1 = 2.;
  /* #218: @6 = (@6/@1) */
  w6 /= w1;
  /* #219: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #220: @1 = (@1*@12) */
  w1 *= w12;
  /* #221: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #222: @1 = (@1*@2) */
  w1 *= w2;
  /* #223: @2 = 2 */
  w2 = 2.;
  /* #224: @1 = (@1/@2) */
  w1 /= w2;
  /* #225: @6 = (@6-@1) */
  w6 -= w1;
  /* #226: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #227: @1 = (@1*@12) */
  w1 *= w12;
  /* #228: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #229: @1 = (@1*@2) */
  w1 *= w2;
  /* #230: @2 = 2 */
  w2 = 2.;
  /* #231: @1 = (@1/@2) */
  w1 /= w2;
  /* #232: @6 = (@6-@1) */
  w6 -= w1;
  /* #233: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #234: @1 = (@1*@12) */
  w1 *= w12;
  /* #235: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #236: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #237: @1 = (@1*@2) */
  w1 *= w2;
  /* #238: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #239: @1 = (@1*@2) */
  w1 *= w2;
  /* #240: @6 = (@6-@1) */
  w6 -= w1;
  /* #241: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #242: @1 = (@1*@12) */
  w1 *= w12;
  /* #243: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #244: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #245: @1 = (@1*@2) */
  w1 *= w2;
  /* #246: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #247: @1 = (@1*@2) */
  w1 *= w2;
  /* #248: @6 = (@6+@1) */
  w6 += w1;
  /* #249: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #250: @1 = (@1*@11) */
  w1 *= w11;
  /* #251: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #252: @1 = (@1*@2) */
  w1 *= w2;
  /* #253: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #254: @1 = (@1*@2) */
  w1 *= w2;
  /* #255: @6 = (@6+@1) */
  w6 += w1;
  /* #256: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #257: @1 = (@1*@11) */
  w1 *= w11;
  /* #258: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #259: @1 = (@1*@2) */
  w1 *= w2;
  /* #260: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #261: @1 = (@1*@2) */
  w1 *= w2;
  /* #262: @6 = (@6-@1) */
  w6 -= w1;
  /* #263: (@16[27] = @6) */
  for (rr=w16+27, ss=(&w6); rr!=w16+28; rr+=1) *rr = *ss++;
  /* #264: @6 = 1.03024e-08 */
  w6 = 1.0302371890782026e-08;
  /* #265: @6 = (@6*@11) */
  w6 *= w11;
  /* #266: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #267: @6 = (@6*@1) */
  w6 *= w1;
  /* #268: @1 = 2 */
  w1 = 2.;
  /* #269: @6 = (@6/@1) */
  w6 /= w1;
  /* #270: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #271: @1 = (@1*@11) */
  w1 *= w11;
  /* #272: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #273: @1 = (@1*@2) */
  w1 *= w2;
  /* #274: @2 = 2 */
  w2 = 2.;
  /* #275: @1 = (@1/@2) */
  w1 /= w2;
  /* #276: @6 = (@6-@1) */
  w6 -= w1;
  /* #277: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #278: @1 = (@1*@11) */
  w1 *= w11;
  /* #279: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #280: @1 = (@1*@2) */
  w1 *= w2;
  /* #281: @2 = 2 */
  w2 = 2.;
  /* #282: @1 = (@1/@2) */
  w1 /= w2;
  /* #283: @6 = (@6-@1) */
  w6 -= w1;
  /* #284: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #285: @1 = (@1*@11) */
  w1 *= w11;
  /* #286: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #287: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #288: @1 = (@1*@2) */
  w1 *= w2;
  /* #289: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #290: @1 = (@1*@2) */
  w1 *= w2;
  /* #291: @6 = (@6-@1) */
  w6 -= w1;
  /* #292: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #293: @1 = (@1*@11) */
  w1 *= w11;
  /* #294: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #295: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #296: @1 = (@1*@2) */
  w1 *= w2;
  /* #297: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #298: @1 = (@1*@2) */
  w1 *= w2;
  /* #299: @6 = (@6+@1) */
  w6 += w1;
  /* #300: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #301: @1 = (@1*@12) */
  w1 *= w12;
  /* #302: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #303: @1 = (@1*@2) */
  w1 *= w2;
  /* #304: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #305: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #306: @1 = (@1*@2) */
  w1 *= w2;
  /* #307: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #308: @1 = (@1*@2) */
  w1 *= w2;
  /* #309: @6 = (@6-@1) */
  w6 -= w1;
  /* #310: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #311: @1 = (@1*@12) */
  w1 *= w12;
  /* #312: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #313: @1 = (@1*@2) */
  w1 *= w2;
  /* #314: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #315: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #316: @1 = (@1*@2) */
  w1 *= w2;
  /* #317: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #318: @1 = (@1*@2) */
  w1 *= w2;
  /* #319: @6 = (@6+@1) */
  w6 += w1;
  /* #320: (@16[33] = @6) */
  for (rr=w16+33, ss=(&w6); rr!=w16+34; rr+=1) *rr = *ss++;
  /* #321: @6 = 1.19721e-08 */
  w6 = 1.1972093549697218e-08;
  /* #322: @6 = (@6*@12) */
  w6 *= w12;
  /* #323: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #324: @6 = (@6*@1) */
  w6 *= w1;
  /* #325: @1 = 2 */
  w1 = 2.;
  /* #326: @6 = (@6/@1) */
  w6 /= w1;
  /* #327: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #328: @1 = (@1*@12) */
  w1 *= w12;
  /* #329: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #330: @1 = (@1*@2) */
  w1 *= w2;
  /* #331: @2 = 2 */
  w2 = 2.;
  /* #332: @1 = (@1/@2) */
  w1 /= w2;
  /* #333: @6 = (@6-@1) */
  w6 -= w1;
  /* #334: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #335: @1 = (@1*@12) */
  w1 *= w12;
  /* #336: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #337: @1 = (@1*@2) */
  w1 *= w2;
  /* #338: @2 = 2 */
  w2 = 2.;
  /* #339: @1 = (@1/@2) */
  w1 /= w2;
  /* #340: @6 = (@6+@1) */
  w6 += w1;
  /* #341: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #342: @1 = (@1*@12) */
  w1 *= w12;
  /* #343: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #344: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #345: @1 = (@1*@2) */
  w1 *= w2;
  /* #346: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #347: @1 = (@1*@2) */
  w1 *= w2;
  /* #348: @6 = (@6+@1) */
  w6 += w1;
  /* #349: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #350: @1 = (@1*@12) */
  w1 *= w12;
  /* #351: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #352: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #353: @1 = (@1*@2) */
  w1 *= w2;
  /* #354: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #355: @1 = (@1*@2) */
  w1 *= w2;
  /* #356: @6 = (@6-@1) */
  w6 -= w1;
  /* #357: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #358: @1 = (@1*@11) */
  w1 *= w11;
  /* #359: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #360: @1 = (@1*@2) */
  w1 *= w2;
  /* #361: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #362: @1 = (@1*@2) */
  w1 *= w2;
  /* #363: @6 = (@6-@1) */
  w6 -= w1;
  /* #364: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #365: @1 = (@1*@11) */
  w1 *= w11;
  /* #366: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #367: @1 = (@1*@2) */
  w1 *= w2;
  /* #368: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #369: @1 = (@1*@2) */
  w1 *= w2;
  /* #370: @6 = (@6+@1) */
  w6 += w1;
  /* #371: (@16[22] = @6) */
  for (rr=w16+22, ss=(&w6); rr!=w16+23; rr+=1) *rr = *ss++;
  /* #372: @6 = 8.6825e-09 */
  w6 = 8.6825002969186300e-09;
  /* #373: @6 = (@6*@10) */
  w6 *= w10;
  /* #374: @1 = cos(@4) */
  w1 = cos( w4 );
  /* #375: @6 = (@6*@1) */
  w6 *= w1;
  /* #376: @1 = sin(@4) */
  w1 = sin( w4 );
  /* #377: @6 = (@6*@1) */
  w6 *= w1;
  /* #378: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #379: @1 = (@1*@10) */
  w1 *= w10;
  /* #380: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #381: @1 = (@1*@2) */
  w1 *= w2;
  /* #382: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #383: @1 = (@1*@2) */
  w1 *= w2;
  /* #384: @6 = (@6-@1) */
  w6 -= w1;
  /* #385: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #386: @6 = 1.19721e-08 */
  w6 = 1.1972093549697218e-08;
  /* #387: @6 = (@6*@10) */
  w6 *= w10;
  /* #388: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #389: @6 = (@6*@1) */
  w6 *= w1;
  /* #390: @1 = 2 */
  w1 = 2.;
  /* #391: @6 = (@6/@1) */
  w6 /= w1;
  /* #392: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #393: @1 = (@1*@10) */
  w1 *= w10;
  /* #394: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #395: @1 = (@1*@2) */
  w1 *= w2;
  /* #396: @2 = 2 */
  w2 = 2.;
  /* #397: @1 = (@1/@2) */
  w1 /= w2;
  /* #398: @6 = (@6-@1) */
  w6 -= w1;
  /* #399: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #400: @1 = (@1*@10) */
  w1 *= w10;
  /* #401: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #402: @1 = (@1*@2) */
  w1 *= w2;
  /* #403: @2 = 2 */
  w2 = 2.;
  /* #404: @1 = (@1/@2) */
  w1 /= w2;
  /* #405: @6 = (@6+@1) */
  w6 += w1;
  /* #406: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #407: @1 = (@1*@10) */
  w1 *= w10;
  /* #408: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #409: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #410: @1 = (@1*@2) */
  w1 *= w2;
  /* #411: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #412: @1 = (@1*@2) */
  w1 *= w2;
  /* #413: @6 = (@6+@1) */
  w6 += w1;
  /* #414: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #415: @1 = (@1*@10) */
  w1 *= w10;
  /* #416: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #417: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #418: @1 = (@1*@2) */
  w1 *= w2;
  /* #419: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #420: @1 = (@1*@2) */
  w1 *= w2;
  /* #421: @6 = (@6-@1) */
  w6 -= w1;
  /* #422: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #423: @1 = (@1*@12) */
  w1 *= w12;
  /* #424: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #425: @1 = (@1*@2) */
  w1 *= w2;
  /* #426: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #427: @1 = (@1*@2) */
  w1 *= w2;
  /* #428: @6 = (@6-@1) */
  w6 -= w1;
  /* #429: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #430: @1 = (@1*@12) */
  w1 *= w12;
  /* #431: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #432: @1 = (@1*@2) */
  w1 *= w2;
  /* #433: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #434: @1 = (@1*@2) */
  w1 *= w2;
  /* #435: @6 = (@6+@1) */
  w6 += w1;
  /* #436: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #437: @1 = (@1*@12) */
  w1 *= w12;
  /* #438: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #439: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #440: @1 = (@1*@2) */
  w1 *= w2;
  /* #441: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #442: @1 = (@1*@2) */
  w1 *= w2;
  /* #443: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #444: @1 = (@1*@2) */
  w1 *= w2;
  /* #445: @6 = (@6-@1) */
  w6 -= w1;
  /* #446: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #447: @1 = (@1*@12) */
  w1 *= w12;
  /* #448: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #449: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #450: @1 = (@1*@2) */
  w1 *= w2;
  /* #451: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #452: @1 = (@1*@2) */
  w1 *= w2;
  /* #453: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #454: @1 = (@1*@2) */
  w1 *= w2;
  /* #455: @6 = (@6+@1) */
  w6 += w1;
  /* #456: (@16[34] = @6) */
  for (rr=w16+34, ss=(&w6); rr!=w16+35; rr+=1) *rr = *ss++;
  /* #457: @6 = 8.6825e-09 */
  w6 = 8.6825002969186300e-09;
  /* #458: @6 = (@6*@11) */
  w6 *= w11;
  /* #459: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #460: @6 = (@6*@1) */
  w6 *= w1;
  /* #461: @1 = 2 */
  w1 = 2.;
  /* #462: @6 = (@6/@1) */
  w6 /= w1;
  /* #463: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #464: @1 = (@1*@11) */
  w1 *= w11;
  /* #465: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #466: @1 = (@1*@2) */
  w1 *= w2;
  /* #467: @2 = 2 */
  w2 = 2.;
  /* #468: @1 = (@1/@2) */
  w1 /= w2;
  /* #469: @6 = (@6-@1) */
  w6 -= w1;
  /* #470: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #471: @1 = (@1*@11) */
  w1 *= w11;
  /* #472: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #473: @1 = (@1*@2) */
  w1 *= w2;
  /* #474: @2 = 2 */
  w2 = 2.;
  /* #475: @1 = (@1/@2) */
  w1 /= w2;
  /* #476: @6 = (@6-@1) */
  w6 -= w1;
  /* #477: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #478: @1 = (@1*@11) */
  w1 *= w11;
  /* #479: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #480: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #481: @1 = (@1*@2) */
  w1 *= w2;
  /* #482: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #483: @1 = (@1*@2) */
  w1 *= w2;
  /* #484: @6 = (@6+@1) */
  w6 += w1;
  /* #485: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #486: @1 = (@1*@11) */
  w1 *= w11;
  /* #487: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #488: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #489: @1 = (@1*@2) */
  w1 *= w2;
  /* #490: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #491: @1 = (@1*@2) */
  w1 *= w2;
  /* #492: @6 = (@6-@1) */
  w6 -= w1;
  /* #493: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #494: @1 = (@1*@12) */
  w1 *= w12;
  /* #495: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #496: @1 = (@1*@2) */
  w1 *= w2;
  /* #497: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #498: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #499: @1 = (@1*@2) */
  w1 *= w2;
  /* #500: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #501: @1 = (@1*@2) */
  w1 *= w2;
  /* #502: @6 = (@6+@1) */
  w6 += w1;
  /* #503: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #504: @1 = (@1*@12) */
  w1 *= w12;
  /* #505: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #506: @1 = (@1*@2) */
  w1 *= w2;
  /* #507: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #508: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #509: @1 = (@1*@2) */
  w1 *= w2;
  /* #510: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #511: @1 = (@1*@2) */
  w1 *= w2;
  /* #512: @6 = (@6-@1) */
  w6 -= w1;
  /* #513: (@16[23] = @6) */
  for (rr=w16+23, ss=(&w6); rr!=w16+24; rr+=1) *rr = *ss++;
  /* #514: @6 = 8.6825e-09 */
  w6 = 8.6825002969186300e-09;
  /* #515: @6 = (@6*@10) */
  w6 *= w10;
  /* #516: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #517: @6 = (@6*@1) */
  w6 *= w1;
  /* #518: @1 = 2 */
  w1 = 2.;
  /* #519: @6 = (@6/@1) */
  w6 /= w1;
  /* #520: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #521: @1 = (@1*@10) */
  w1 *= w10;
  /* #522: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #523: @1 = (@1*@2) */
  w1 *= w2;
  /* #524: @2 = 2 */
  w2 = 2.;
  /* #525: @1 = (@1/@2) */
  w1 /= w2;
  /* #526: @6 = (@6-@1) */
  w6 -= w1;
  /* #527: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #528: @1 = (@1*@10) */
  w1 *= w10;
  /* #529: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #530: @1 = (@1*@2) */
  w1 *= w2;
  /* #531: @2 = 2 */
  w2 = 2.;
  /* #532: @1 = (@1/@2) */
  w1 /= w2;
  /* #533: @6 = (@6-@1) */
  w6 -= w1;
  /* #534: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #535: @1 = (@1*@10) */
  w1 *= w10;
  /* #536: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #537: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #538: @1 = (@1*@2) */
  w1 *= w2;
  /* #539: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #540: @1 = (@1*@2) */
  w1 *= w2;
  /* #541: @6 = (@6+@1) */
  w6 += w1;
  /* #542: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #543: @1 = (@1*@10) */
  w1 *= w10;
  /* #544: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #545: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #546: @1 = (@1*@2) */
  w1 *= w2;
  /* #547: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #548: @1 = (@1*@2) */
  w1 *= w2;
  /* #549: @6 = (@6-@1) */
  w6 -= w1;
  /* #550: @1 = 1.19721e-08 */
  w1 = 1.1972093549697218e-08;
  /* #551: @1 = (@1*@12) */
  w1 *= w12;
  /* #552: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #553: @1 = (@1*@2) */
  w1 *= w2;
  /* #554: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #555: @1 = (@1*@2) */
  w1 *= w2;
  /* #556: @6 = (@6+@1) */
  w6 += w1;
  /* #557: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #558: @1 = (@1*@12) */
  w1 *= w12;
  /* #559: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #560: @1 = (@1*@2) */
  w1 *= w2;
  /* #561: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #562: @1 = (@1*@2) */
  w1 *= w2;
  /* #563: @6 = (@6-@1) */
  w6 -= w1;
  /* #564: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #565: @1 = (@1*@12) */
  w1 *= w12;
  /* #566: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #567: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #568: @1 = (@1*@2) */
  w1 *= w2;
  /* #569: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #570: @1 = (@1*@2) */
  w1 *= w2;
  /* #571: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #572: @1 = (@1*@2) */
  w1 *= w2;
  /* #573: @6 = (@6+@1) */
  w6 += w1;
  /* #574: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #575: @1 = (@1*@12) */
  w1 *= w12;
  /* #576: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #577: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #578: @1 = (@1*@12) */
  w1 *= w12;
  /* #579: @12 = cos(@5) */
  w12 = cos( w5 );
  /* #580: @1 = (@1*@12) */
  w1 *= w12;
  /* #581: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #582: @1 = (@1*@12) */
  w1 *= w12;
  /* #583: @6 = (@6-@1) */
  w6 -= w1;
  /* #584: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #585: @1 = (@1*@11) */
  w1 *= w11;
  /* #586: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #587: @1 = (@1*@12) */
  w1 *= w12;
  /* #588: @12 = sin(@4) */
  w12 = sin( w4 );
  /* #589: @1 = (@1*@12) */
  w1 *= w12;
  /* #590: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #591: @1 = (@1*@12) */
  w1 *= w12;
  /* #592: @6 = (@6-@1) */
  w6 -= w1;
  /* #593: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #594: @1 = (@1*@11) */
  w1 *= w11;
  /* #595: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #596: @1 = (@1*@12) */
  w1 *= w12;
  /* #597: @12 = sin(@4) */
  w12 = sin( w4 );
  /* #598: @1 = (@1*@12) */
  w1 *= w12;
  /* #599: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #600: @1 = (@1*@12) */
  w1 *= w12;
  /* #601: @6 = (@6+@1) */
  w6 += w1;
  /* #602: (@16[29] = @6) */
  for (rr=w16+29, ss=(&w6); rr!=w16+30; rr+=1) *rr = *ss++;
  /* #603: @6 = 1.19721e-08 */
  w6 = 1.1972093549697218e-08;
  /* #604: @6 = (@6*@11) */
  w6 *= w11;
  /* #605: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #606: @6 = (@6*@1) */
  w6 *= w1;
  /* #607: @1 = sin(@5) */
  w1 = sin( w5 );
  /* #608: @6 = (@6*@1) */
  w6 *= w1;
  /* #609: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #610: @1 = (@1*@11) */
  w1 *= w11;
  /* #611: @12 = cos(@5) */
  w12 = cos( w5 );
  /* #612: @1 = (@1*@12) */
  w1 *= w12;
  /* #613: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #614: @1 = (@1*@12) */
  w1 *= w12;
  /* #615: @6 = (@6-@1) */
  w6 -= w1;
  /* #616: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #617: @1 = (@1*@10) */
  w1 *= w10;
  /* #618: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #619: @1 = (@1*@12) */
  w1 *= w12;
  /* #620: @12 = cos(@5) */
  w12 = cos( w5 );
  /* #621: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #622: @1 = (@1*@12) */
  w1 *= w12;
  /* #623: @12 = sin(@4) */
  w12 = sin( w4 );
  /* #624: @1 = (@1*@12) */
  w1 *= w12;
  /* #625: @6 = (@6+@1) */
  w6 += w1;
  /* #626: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #627: @1 = (@1*@10) */
  w1 *= w10;
  /* #628: @10 = cos(@4) */
  w10 = cos( w4 );
  /* #629: @1 = (@1*@10) */
  w1 *= w10;
  /* #630: @10 = cos(@5) */
  w10 = cos( w5 );
  /* #631: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #632: @1 = (@1*@10) */
  w1 *= w10;
  /* #633: @10 = sin(@4) */
  w10 = sin( w4 );
  /* #634: @1 = (@1*@10) */
  w1 *= w10;
  /* #635: @6 = (@6-@1) */
  w6 -= w1;
  /* #636: @1 = 1.03024e-08 */
  w1 = 1.0302371890782026e-08;
  /* #637: @1 = (@1*@11) */
  w1 *= w11;
  /* #638: @10 = cos(@4) */
  w10 = cos( w4 );
  /* #639: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #640: @1 = (@1*@10) */
  w1 *= w10;
  /* #641: @10 = cos(@5) */
  w10 = cos( w5 );
  /* #642: @1 = (@1*@10) */
  w1 *= w10;
  /* #643: @10 = sin(@5) */
  w10 = sin( w5 );
  /* #644: @1 = (@1*@10) */
  w1 *= w10;
  /* #645: @6 = (@6+@1) */
  w6 += w1;
  /* #646: @1 = 8.6825e-09 */
  w1 = 8.6825002969186300e-09;
  /* #647: @1 = (@1*@11) */
  w1 *= w11;
  /* #648: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #649: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #650: @1 = (@1*@4) */
  w1 *= w4;
  /* #651: @4 = cos(@5) */
  w4 = cos( w5 );
  /* #652: @1 = (@1*@4) */
  w1 *= w4;
  /* #653: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #654: @1 = (@1*@5) */
  w1 *= w5;
  /* #655: @6 = (@6-@1) */
  w6 -= w1;
  /* #656: (@16[35] = @6) */
  for (rr=w16+35, ss=(&w6); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #657: @32 = @13[6:12] */
  for (rr=w32, ss=w13+6; ss!=w13+12; ss+=1) *rr++ = *ss;
  /* #658: @31 = mac(@16,@32,@31) */
  for (i=0, rr=w31; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #659: @30 = (@30-@31) */
  for (i=0, rr=w30, cs=w31; i<6; ++i) (*rr++) -= (*cs++);
  /* #660: @31 = zeros(6x1) */
  casadi_clear(w31, 6);
  /* #661: @6 = 1.49994e-07 */
  w6 = 1.4999363378617051e-07;
  /* #662: (@31[2] = @6) */
  for (rr=w31+2, ss=(&w6); rr!=w31+3; rr+=1) *rr = *ss++;
  /* #663: @30 = (@30-@31) */
  for (i=0, rr=w30, cs=w31; i<6; ++i) (*rr++) -= (*cs++);
  /* #664: @14 = mac(@15,@30,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w15+j, tt=w30+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #665: (@0[6:12] = @14) */
  for (rr=w0+6, ss=w14; rr!=w0+12; rr+=1) *rr = *ss++;
  /* #666: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 375;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
